function ErrEstJump = aPostErrEstJump(eleCase,longestEdgeLength,CSTStrain,CSTNeighborAtBoundaryCheck)



switch eleCase
    
    case 1
        ErrEstJump = CSTNeighborAtBoundaryCheck(4)*longestEdgeLength*((1/sqrt(2)*(CSTStrain(4,1)+CSTStrain(4,2)-CSTStrain(1,1)-CSTStrain(1,2)))^2 + ...
            (1/sqrt(2)*(CSTStrain(4,3)+CSTStrain(4,4)-CSTStrain(1,3)-CSTStrain(1,4)))^2) + ...
            CSTNeighborAtBoundaryCheck(2)*longestEdgeLength/sqrt(2)*((-CSTStrain(2,1)+CSTStrain(1,1))^2 + (-CSTStrain(2,3)+CSTStrain(1,3))^2) + ...
            CSTNeighborAtBoundaryCheck(3)*longestEdgeLength/sqrt(2)*((-CSTStrain(3,2)+CSTStrain(1,2))^2 + (-CSTStrain(3,4)+CSTStrain(1,4))^2);
        
    case 2
        ErrEstJump = CSTNeighborAtBoundaryCheck(2)*longestEdgeLength/sqrt(2)*((1/sqrt(2)*(-CSTStrain(2,1)-CSTStrain(2,2)+CSTStrain(1,1)+CSTStrain(1,2)))^2+ ...
            (1/sqrt(2)*(-CSTStrain(2,3)-CSTStrain(2,4)+CSTStrain(1,3)+CSTStrain(1,4)))^2) + ...
            CSTNeighborAtBoundaryCheck(3)*longestEdgeLength/sqrt(2)*((1/sqrt(2)*(CSTStrain(3,1)-CSTStrain(3,2)-CSTStrain(1,1)+CSTStrain(1,2)))^2 + ...
            (1/sqrt(2)*(CSTStrain(3,3)-CSTStrain(3,4)-CSTStrain(1,3)+CSTStrain(1,4)))^2) + ...
            CSTNeighborAtBoundaryCheck(4)*longestEdgeLength*((CSTStrain(4,2)-CSTStrain(1,2))^2 + (CSTStrain(4,4)-CSTStrain(1,4))^2);
        
    case 3
        ErrEstJump = CSTNeighborAtBoundaryCheck(4)*longestEdgeLength*((1/sqrt(2)*(-CSTStrain(4,1)+CSTStrain(4,2)+CSTStrain(1,1)-CSTStrain(1,2)))^2 + ...
            (1/sqrt(2)*(-CSTStrain(4,3)+CSTStrain(4,4)+CSTStrain(1,3)-CSTStrain(1,4)))^2) + ...
            CSTNeighborAtBoundaryCheck(2)*longestEdgeLength/sqrt(2)*((-CSTStrain(2,2)+CSTStrain(1,2))^2 + (-CSTStrain(2,4)+CSTStrain(1,4))^2) + ...
            CSTNeighborAtBoundaryCheck(3)*longestEdgeLength/sqrt(2)*((-CSTStrain(3,1)+CSTStrain(1,1))^2 + (-CSTStrain(3,3)+CSTStrain(1,3))^2);
        
    case 4
        ErrEstJump = CSTNeighborAtBoundaryCheck(2)*longestEdgeLength/sqrt(2)*((1/sqrt(2)*(CSTStrain(2,1)-CSTStrain(2,2)-CSTStrain(1,1)+CSTStrain(1,2)))^2+ ...
            (1/sqrt(2)*(CSTStrain(2,3)-CSTStrain(2,4)-CSTStrain(1,3)+CSTStrain(1,4)))^2) + ...
            CSTNeighborAtBoundaryCheck(3)*longestEdgeLength/sqrt(2)*((1/sqrt(2)*(CSTStrain(3,1)+CSTStrain(3,2)-CSTStrain(1,1)-CSTStrain(1,2)))^2 + ...
            (1/sqrt(2)*(CSTStrain(3,3)+CSTStrain(3,4)-CSTStrain(1,3)-CSTStrain(1,4)))^2) + ...
            CSTNeighborAtBoundaryCheck(4)*longestEdgeLength*((-CSTStrain(4,1)+CSTStrain(1,1))^2 + (-CSTStrain(4,3)+CSTStrain(1,3))^2);
        
    case 5
         ErrEstJump = CSTNeighborAtBoundaryCheck(4)*longestEdgeLength*((1/sqrt(2)*(-CSTStrain(4,1)-CSTStrain(4,2)+CSTStrain(1,1)+CSTStrain(1,2)))^2 + ...
            (1/sqrt(2)*(-CSTStrain(4,3)-CSTStrain(4,4)+CSTStrain(1,3)+CSTStrain(1,4)))^2) + ...
            CSTNeighborAtBoundaryCheck(2)*longestEdgeLength/sqrt(2)*((CSTStrain(2,1)-CSTStrain(1,1))^2 + (CSTStrain(2,3)-CSTStrain(1,3))^2) + ...
            CSTNeighborAtBoundaryCheck(3)*longestEdgeLength/sqrt(2)*((CSTStrain(3,2)-CSTStrain(1,2))^2 + (CSTStrain(3,4)-CSTStrain(1,4))^2);
        
    case 6
        ErrEstJump = CSTNeighborAtBoundaryCheck(2)*longestEdgeLength/sqrt(2)*((1/sqrt(2)*(CSTStrain(2,1)+CSTStrain(2,2)-CSTStrain(1,1)-CSTStrain(1,2)))^2+ ...
            (1/sqrt(2)*(CSTStrain(2,3)+CSTStrain(2,4)-CSTStrain(1,3)-CSTStrain(1,4)))^2) + ...
            CSTNeighborAtBoundaryCheck(3)*longestEdgeLength/sqrt(2)*((1/sqrt(2)*(-CSTStrain(3,1)+CSTStrain(3,2)+CSTStrain(1,1)-CSTStrain(1,2)))^2 + ...
            (1/sqrt(2)*(-CSTStrain(3,3)+CSTStrain(3,4)+CSTStrain(1,3)-CSTStrain(1,4)))^2) + ...
            CSTNeighborAtBoundaryCheck(4)*longestEdgeLength*((-CSTStrain(4,2)+CSTStrain(1,2))^2 + (-CSTStrain(4,4)+CSTStrain(1,4))^2);
        
    case 7
        ErrEstJump = CSTNeighborAtBoundaryCheck(4)*longestEdgeLength*((1/sqrt(2)*(CSTStrain(4,1)-CSTStrain(4,2)-CSTStrain(1,1)+CSTStrain(1,2)))^2 + ...
            (1/sqrt(2)*(CSTStrain(4,3)-CSTStrain(4,4)-CSTStrain(1,3)+CSTStrain(1,4)))^2) + ...
            CSTNeighborAtBoundaryCheck(2)*longestEdgeLength/sqrt(2)*((CSTStrain(2,2)-CSTStrain(1,2))^2 + (CSTStrain(2,4)-CSTStrain(1,4))^2) + ...
            CSTNeighborAtBoundaryCheck(3)*longestEdgeLength/sqrt(2)*((-CSTStrain(3,1)+CSTStrain(1,1))^2 + (-CSTStrain(3,3)+CSTStrain(1,3))^2);
        
    case 8
        ErrEstJump = CSTNeighborAtBoundaryCheck(2)*longestEdgeLength/sqrt(2)*((1/sqrt(2)*(-CSTStrain(2,1)+CSTStrain(2,2)+CSTStrain(1,1)-CSTStrain(1,2)))^2+ ...
            (1/sqrt(2)*(-CSTStrain(2,3)+CSTStrain(2,4)+CSTStrain(1,3)-CSTStrain(1,4)))^2) + ...
            CSTNeighborAtBoundaryCheck(3)*longestEdgeLength/sqrt(2)*((1/sqrt(2)*(-CSTStrain(3,1)-CSTStrain(3,2)+CSTStrain(1,1)+CSTStrain(1,2)))^2 + ...
            (1/sqrt(2)*(-CSTStrain(3,3)-CSTStrain(3,4)+CSTStrain(1,3)+CSTStrain(1,4)))^2) + ...
            CSTNeighborAtBoundaryCheck(4)*longestEdgeLength*((CSTStrain(4,1)-CSTStrain(1,1))^2 + (CSTStrain(4,3)-CSTStrain(1,3))^2);
        
    otherwise
        ErrEstJump = 0;
        
end